### ISSUE TITLE
highlight error on string with commas

### ISSUE THREAD

**Issue by UziTech** [Gert-dev/php-integrator-call-tips#3]
string parameters with commas make the tip highlight the wrong parameter
![php-integrator-call-tips](https://cloud.githubusercontent.com/assets/97994/14754726/d686a3bc-08a2-11e6-809f-f517a3e9943e.gif)

**Comment by Gert-dev** [comment]
Thanks for reporting this, it was actually a bug in the base package. It should be fixed in the just-released 0.8.2.
